#
# Splunk app configuration file
#

[install]
is_configured = 1
install_source_checksum = 822eb1abe3866ceeb4cac97393c182cadf1bce22

[ui]
is_visible = 1
label = myViz360

[launcher]
author = Darl Jed Matundan
description = Custom single value visualization
version = 1.0.5

