#
# Splunk app configuration file
#

[install]
is_configured = 1
install_source_checksum = 5c3a34e0a580653611356a7f6281aea13cb2e54c

[ui]
is_visible = 1
label = myViz360

[launcher]
author = Darl Jed Matundan
description = Custom single value visualization
version = 1.0.5

